<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Teacher Staff — 07_Data_Dictionary.md §30.
 *
 * "Represents an internal user created by a Teacher inside a Teacher
 * Workspace." Never called sub-teacher (§30 Notes).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('teacher_staff', function (Blueprint $table): void {
            // "Teacher Staff Identifier | Identifier | Required | Generated by
            // system | Must be unique." (§30)
            $table->id();

            // "User Reference | Reference | Required | Must reference valid
            // User." (§30)
            $table->foreignId('user_id')->constrained('users')->restrictOnDelete();

            // "Teacher Workspace Reference | Reference | Required | Must
            // reference creating Teacher Workspace." (§30)
            $table->foreignId('teacher_workspace_id')
                ->constrained('teacher_workspaces')
                ->restrictOnDelete();

            // "Staff Type Label | Text | Optional | Examples include
            // Secretary, Assistant, Accountant." (§30)
            // Free text, not an enum: the dictionary calls these examples, and
            // 33_Validation_Rules.md §3.3 lists no confirmed set for it.
            $table->string('staff_type_label', 190)->nullable();

            // "Account Status | Status | Required | Active | Archived staff
            // cannot act actively." (§30)
            $table->string('account_status', 32)->default('active');

            // "Created At | DateTime | Required | Current server time" (§30)
            $table->timestamps();

            // "Archived State | Archive State | Required | Active" (§30)
            $table->timestamp('archived_at')->nullable();

            // "Teacher Staff exist only inside the creating Teacher
            // Workspace." (§30; 06 §12) A User holds one Teacher Staff context
            // per workspace.
            $table->unique(['user_id', 'teacher_workspace_id']);

            // 06_Database_Design.md §10: tenant scope and archive filtering.
            $table->index(['teacher_workspace_id', 'archived_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('teacher_staff');
    }
};
