<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Teacher — 07_Data_Dictionary.md §4.
 *
 * "Represents a paying customer who operates one isolated Teacher Workspace."
 *
 * Not carried in this phase: "Subscription Status Reference | Reference |
 * Optional | Must relate to Flow A only." Subscriptions are a later phase, and
 * adding a column for a table that does not exist would be speculative.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('teachers', function (Blueprint $table): void {
            // "Teacher Identifier | Identifier | Required | Generated by
            // system | Must be unique." (§4)
            $table->id();

            // "User Reference | Reference | Required | Must reference a valid
            // User." (§4)
            $table->foreignId('user_id')->constrained('users')->restrictOnDelete();

            // "Teacher Workspace Reference | Reference | Required | Must
            // reference the Teacher's own Teacher Workspace." (§4)
            $table->foreignId('teacher_workspace_id')
                ->constrained('teacher_workspaces')
                ->restrictOnDelete();

            // "Teaching Subject Reference | Reference | Required | Must be
            // selected once and cannot change after account creation." (§4)
            $table->foreignId('teaching_subject_id')
                ->constrained('teaching_subjects')
                ->restrictOnDelete();

            // "Account Status | Status | Required | Active" (§4)
            $table->string('account_status', 32)->default('active');

            // "Created At | DateTime | Required | Current server time" (§4)
            $table->timestamps();

            // "Archived State | Archive State | Required | Active" (§4)
            $table->timestamp('archived_at')->nullable();

            // "Teacher has one Teacher Workspace." (§4 Relationships) and
            // 06_Database_Design.md §12: "Each Teacher account has one Teacher
            // Workspace." A unique constraint is the mathematically necessary
            // way to enforce a one-to-one relationship in the schema.
            $table->unique('teacher_workspace_id');

            // A User is a global identity (§1); the Teacher context derived
            // from it is singular, so the reference is unique.
            $table->unique('user_id');

            // 06_Database_Design.md §10: archive-state filtering.
            $table->index('archived_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('teachers');
    }
};
