<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Teacher Workspace — 07_Data_Dictionary.md §5.
 *
 * "Represents one Teacher's completely isolated area of the Platform" and is
 * the tenant boundary (06_Database_Design.md §6).
 *
 * Table name mandated by 28_Coding_Standards.md §12: `teacher_workspaces`,
 * never `tenants`.
 *
 * The required Teacher Reference (§5) is added by a later migration, because
 * Teacher also holds a required Teacher Workspace Reference (§4). The two
 * entities reference each other, so one direction must be added after both
 * tables exist. See PHYSICAL_SCHEMA_DECISIONS.md DD-02.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('teacher_workspaces', function (Blueprint $table): void {
            // "Teacher Workspace Identifier | Identifier | Required |
            // Generated by system | Must be unique." (§5)
            $table->id();

            // "Workspace Status | Status | Required | Active | Must reflect
            // allowed workspace state." (§5)
            // 33_Validation_Rules.md INT-15 requires persisted statuses to be
            // valid states; the dictionary documents the Active default and
            // does not enumerate further workspace states, so the column is a
            // constrained string rather than a fabricated enum set.
            // See PHYSICAL_SCHEMA_DECISIONS.md DD-04.
            $table->string('workspace_status', 32)->default('active');

            // "Created At | DateTime | Required | Current server time" (§5)
            $table->timestamps();

            // "Archived State | Archive State | Required | Active" (§5)
            $table->timestamp('archived_at')->nullable();

            // 06_Database_Design.md §10: archive-state filtering.
            $table->index('archived_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('teacher_workspaces');
    }
};
