<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Permission — 07_Data_Dictionary.md §3.
 *
 * "Represents a capability that can be granted within the Platform, especially
 * for Teacher Staff."
 *
 * PENDING Q-011. The dictionary is explicit: "Teacher Staff permission
 * granularity remains PENDING and must not be silently assumed" and "the final
 * permission catalog must be defined in RBAC documentation."
 *
 * The structure is therefore created, but **no permission is seeded**. The
 * catalog stays empty until Q-011 is formally resolved, so nothing here
 * hardens a pending decision.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('permissions', function (Blueprint $table): void {
            // "Permission Identifier | Identifier | Required | Generated by
            // system | Must be unique." (§3)
            $table->id();

            // "Permission Name | Text | Required | Must represent a valid
            // capability." (§3)
            $table->string('permission_name', 190);

            // "Permission Scope | Enum | Required | Teacher Workspace | Must
            // not exceed the owning role scope." (§3)
            // The scope set is the Role Scope set (33_Validation_Rules.md
            // §3.3), because §3 constrains a Permission Scope never to exceed
            // its owning role scope — the two are drawn from the same domain.
            $table->enum('permission_scope', [
                'platform',
                'teacher_workspace',
                'student_account',
                'parent_linked_students',
            ])->default('teacher_workspace');

            // "Permission Status | Status | Required | Active | Must be active
            // to be assigned." (§3)
            $table->string('permission_status', 32)->default('active');

            $table->timestamps();

            // "Archived State | Archive State | Required | Active" (§3)
            $table->timestamp('archived_at')->nullable();

            // "Permission Identifier ... Must be unique" applies to the
            // identifier; a capability is also identified by its name within
            // its scope, so the pair is unique.
            $table->unique(['permission_name', 'permission_scope']);

            $table->index('archived_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('permissions');
    }
};
