<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Student — 07_Data_Dictionary.md §6.
 *
 * "Represents a learner with one global account who may study with multiple
 * Teachers." Student identity is global; Teacher-specific academic data stays
 * partitioned per Teacher (§6 Notes).
 *
 * Phase 43B scope: this table completes the database contract so Phase 44 can
 * implement every documented authentication endpoint without a further
 * migration. It carries the Student entity only — no Teacher Student
 * Relationship, no Enrollment, no Parent Student Link. Those are separate
 * logical entities (06_Database_Design.md §4) owned by later phases.
 *
 * The table deliberately holds no teacher_workspace_id: a Student is global
 * and may study with multiple Teachers (BR-001), so a workspace column here
 * would contradict the entity.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('students', function (Blueprint $table): void {
            // "Student Identifier | Identifier | Required | Generated by
            // system | Must be unique." (§6)
            $table->id();

            // "User Reference | Reference | Required | Must reference one
            // global User." (§6)
            $table->foreignId('user_id')->constrained('users')->restrictOnDelete();

            // "Activation Status | Status | Required | Active or Pending
            // Activation | Must support Teacher-created account activation."
            // (§6)
            //
            // A database enum, unlike the other status columns: 33 STU-02
            // confirms the set as closed — "Active, Pending Activation. Other
            // values are invalid." Contrast account_status below.
            //
            // No default is declared, because the correct initial value
            // depends on the registration method (§6 Business Rules): a
            // self-registered account differs from a Teacher-created one. The
            // dictionary lists both values in the Default column rather than
            // naming one, so choosing a default here would invent a decision.
            $table->enum('activation_status', ['active', 'pending_activation']);

            // "Account Status | Status | Required | Active | Must represent
            // allowed Student account state." (§6)
            //
            // A constrained string, not an enum: the dictionary documents the
            // Active default but never enumerates the complete set, and
            // 33 §3.4 forbids inventing values. Consistent with DD-04.
            $table->string('account_status', 32)->default('active');

            // "Created By Method | Enum | Required | Must be Self-Registration
            // or Teacher-Created." (§6)
            // Confirmed closed set — 33 §3.3 "Student Created By Method";
            // 33 STU-01: "No third method exists in Version 1."
            $table->enum('created_by_method', ['self_registration', 'teacher_created']);

            // "Created At | DateTime | Required | Current server time" (§6)
            $table->timestamps();

            // "Archived State | Archive State | Required | Active | Must
            // follow Archive policy." (§6)
            // Column name mandated by 28_Coding_Standards.md §12.5.
            $table->timestamp('archived_at')->nullable();

            // "A Student has exactly one global account." (§6 Business Rules;
            // BR-001) and "Duplicate Student accounts are not allowed."
            // (BR-022). One User identity resolves to at most one Student
            // record, so the reference is unique. This is the schema-level
            // half of duplicate prevention; identity-level duplicate detection
            // at registration is a Phase 44 write-path rule.
            $table->unique('user_id');

            // 06_Database_Design.md §10: "Student global identity uniqueness"
            // and "Archive state filtering for active versus archived
            // records."
            $table->index('archived_at');

            // 33 AUT-13 requires resolving "exactly one pending-activation
            // Teacher-created account" during activation. That lookup filters
            // on both columns together, so the composite index serves the
            // documented access path rather than a speculative one.
            $table->index(['activation_status', 'created_by_method']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('students');
    }
};
