<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Role — 07_Data_Dictionary.md §2.
 *
 * "Represents one of the confirmed Version 1 user roles."
 *
 * Version 1 has exactly five roles and four role scopes. Both sets are closed
 * and confirmed by 33_Validation_Rules.md §3.3, so they are expressed as
 * database enums: an out-of-set value is rejected by the engine, not only by
 * the application.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('roles', function (Blueprint $table): void {
            // "Role Identifier | Identifier | Required | Generated by system |
            // Must be unique." (§2)
            $table->id();

            // "Role Name | Enum | Required | Must be one of: Super Admin,
            // Teacher, Teacher Staff, Student, Parent." (§2)
            // Confirmed closed set — 33_Validation_Rules.md §3.3 "Role".
            $table->enum('role_name', [
                'super_admin',
                'teacher',
                'teacher_staff',
                'student',
                'parent',
            ]);

            // "Role Scope | Enum | Required | Must match role boundary:
            // Platform, Teacher Workspace, Student Account, or Parent Linked
            // Students." (§2)
            // Confirmed closed set — 33_Validation_Rules.md §3.3 "Role Scope".
            $table->enum('role_scope', [
                'platform',
                'teacher_workspace',
                'student_account',
                'parent_linked_students',
            ]);

            // "Description | Text | Optional | Must describe role
            // responsibility without adding unconfirmed permissions." (§2)
            $table->string('description', 255)->nullable();

            $table->timestamps();

            // "Archived State | Archive State | Required | Active" (§2)
            $table->timestamp('archived_at')->nullable();

            // "Version 1 has exactly five roles" (§2 Business Rules). A role
            // name identifies exactly one role record, so it is unique.
            $table->unique('role_name');

            $table->index('archived_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('roles');
    }
};
