<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Audit Log — 07_Data_Dictionary.md §27.
 *
 * "Represents an append-only record of important actions." Entries are
 * append-only, immutable, and permanently retained
 * (06_Database_Design.md §8; 23_Security_Standards.md §15.4).
 *
 * Table name mandated by 28_Coding_Standards.md §12: `audit_log_entries`.
 *
 * Deliberately absent: an `archived_at` column. §27 is the only foundational
 * entity whose attribute table declares **no** Archived State, and its Notes
 * are explicit: "Audit Log records are not archived or deleted." Adding one
 * would contradict the specification.
 *
 * Also absent: `updated_at`. An immutable record is never updated, so an
 * update timestamp could only ever mislead. See PHYSICAL_SCHEMA_DECISIONS.md
 * DD-06.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('audit_log_entries', function (Blueprint $table): void {
            // "Audit Log Identifier | Identifier | Required | Generated by
            // system | Must be unique." (§27)
            $table->id();

            // "Actor Reference | Reference | Required | Must reference the
            // actual actor where available." (§27)
            // Nullable strictly because of "where available": a failed login
            // is a mandatory audit event (23 §15.2 item 5) that may carry no
            // resolvable actor. See PHYSICAL_SCHEMA_DECISIONS.md DD-07.
            $table->foreignId('actor_user_id')
                ->nullable()
                ->constrained('users')
                ->restrictOnDelete();

            // "Actor Role | Enum | Required | Must reflect role at time of
            // action." (§27) Stored as a value, not a reference: the role at
            // the time of the action must survive later role changes.
            $table->enum('actor_role', [
                'super_admin',
                'teacher',
                'teacher_staff',
                'student',
                'parent',
            ])->nullable();

            // "Scope Context | Enum | Required | Must be Platform or Teacher
            // Workspace context." (§27; confirmed set 33 §3.3)
            $table->enum('scope_context', ['platform', 'teacher_workspace']);

            // "May be scoped to Platform or Teacher Workspace." (§27)
            // Null for Platform-scope events, set for workspace-scope events.
            $table->foreignId('teacher_workspace_id')
                ->nullable()
                ->constrained('teacher_workspaces')
                ->restrictOnDelete();

            // "Event Type | Enum | Required | Must be one of the confirmed
            // audited event types." (§27)
            // Closed set confirmed by 33 §3.3 and 23 §15.2.
            $table->enum('event_type', [
                'create',
                'update',
                'archive',
                'restore',
                'login',
                'permission_change',
                'attendance_change',
                'exam_modification',
                'homework_modification',
                'subscription_change',
            ]);

            // "Affected Entity Name | Text | Required | Must identify affected
            // logical entity." (§27)
            $table->string('affected_entity_name', 190);

            // "Affected Entity Reference | Reference | Optional | Required
            // when action affects a record." (§27)
            // Not a foreign key: it points at any logical entity across the
            // Platform, and it must remain valid for historical traceability
            // "even when the affected record is archived" (06 §8).
            $table->unsignedBigInteger('affected_entity_id')->nullable();

            // "Event Details | Structured Data | Optional | Must preserve
            // meaningful audit context." (§27)
            // 23 §15.3 requires a before/after snapshot of changed fields.
            $table->json('event_details')->nullable();

            // 23 §15.3 "Origin: timestamp (server time), IP address, and
            // device/client information."
            $table->string('ip_address', 45)->nullable();
            $table->text('user_agent')->nullable();

            // "Occurred At | DateTime | Required | Current server time |
            // Must be system-generated." (§27)
            $table->timestamp('occurred_at');

            // Append-only: creation time is recorded, and no updated_at exists.
            $table->timestamp('created_at')->nullable();

            // 06_Database_Design.md §10: "Audit Log lookup by actor, event
            // type, scope, and time context."
            $table->index(['actor_user_id', 'occurred_at']);
            $table->index(['event_type', 'occurred_at']);
            $table->index(['scope_context', 'occurred_at']);
            $table->index(['teacher_workspace_id', 'occurred_at']);

            // "References affected logical entity where applicable." (§27)
            // Supports tracing the full history of one record.
            $table->index(['affected_entity_name', 'affected_entity_id']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('audit_log_entries');
    }
};
